<?php
namespace app\controllers;

use Yii;
use yii\web\ErrorAction;

class Controller extends \yii\web\Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        if($this->id !== 'install' && !isset(Yii::$app->params['isInstall'])){
            return $this->redirect('/install');
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}